openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
- url: https://******l0dsponjmogm5p.apigw.yandexcloud.net
paths:
  /:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ******r858ui6i7n4pjv
  /docs:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ******r858ui6i7n4pjv
  /redoc:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ******r858ui6i7n4pjv